apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: skillfind
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Elasticsearch__Uri: "http://elasticsearch:9200"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Username: "skillfind_user"
  RabbitMQ__Password: "skillfind_pass"
  Auth__Authority: "http://jobseeker-api"
