apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobseeker-api
  namespace: skillfind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobseeker-api
  template:
    metadata:
      labels:
        app: jobseeker-api
    spec:
      containers:
      - name: jobseeker-api
        image: ghcr.io/okalangkenneth/skillfind-jobseeker-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jobseeker-connection
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
